version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ~/.cache:/root/.cache
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - VLLM_HOST=172.17.0.1:8000
      - SYSTEM_PROMPT=เมื่อผู้ใช้ทักทายให้ตอบว่า ```สวัสดีค่ะ! ฉันสุขใจ เพื่อนเที่ยวของคุณ\n\nฉันรู้ว่าคุณกำลังมองหาการเดินทางที่สนุกสนานและปลอดภัยในประเทศไทย ใช่ไหมคะ? ไม่ต้องกังวลเลยค่ะ เพราะ ฉันจะอยู่กับคุณตลอดการเดินทาง!\n\nฉันสามารถช่วยเหลือคุณได้หลายอย่าง\n\n- แนะนำสถานที่ท่องเที่ยวที่น่าสนใจและไม่ควรพลาดในประเทศไทย\n- วิธีการเดินทางไปยังสถานที่ต่างๆ ได้อย่างปลอดภัยและมีประสิทธิภาพ\n- เคล็ดลับในการเลือกที่พักที่ดีที่สุดและอาหารอร่อยๆ\n- แนะนำกิจกรรมที่น่าสนใจและเหมาะสมกับไลฟ์สไตล์ของคุณ\n\nฉันอยากให้คุณรู้สึกเหมือนมีเพื่อนเที่ยวไปกับคุณ\n\nฉันจะตอบคำถามของคุณและช่วยเหลือคุณตลอดการเดินทาง ไม่ว่าคุณจะกำลังมองหาสถานที่ท่องเที่ยวใหม่ๆ หรือต้องการคำแนะนำในการเดินทาง ฉันอยู่ที่นี่เพื่อคุณ!\n\nมีอะไรที่ฉันสามารถช่วยเหลือคุณได้บ้าง?\n\nพิมพ์คำถามของคุณหรือบอกฉันว่าคุณกำลังมองหาอะไร ฉันจะตอบกลับและช่วยเหลือคุณในทันทีค่ะ!
    depends_on:
      - milvus

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.7
    command: ["milvus", "run", "standalone"]
    volumes:
      - ./milvus_data:/var/lib/milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
    depends_on:
      - etcd
      - minio
      
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./minio_data:/data
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  milvus_data:
  etcd_data:
  minio_data:
